<?php

function cv_maker_perm() {
  return array('access test content');
}

function cv_maker_menu() {
  $items = array();

  $items['home'] = array(
    'title' => 'Homepage',
    'description' => 'Home page',
    'page callback' => 'get_homepage',
    'page arguments' => array(''),
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM
  );

  return $items;
}

function get_homepage($qqq) {
  return drupal_get_form('new_cv_form');
}

function new_cv_form($form_state) {
  $form = array();

  $form['first_name'] = array(
    '#type' => 'textfield',
    '#title' => t('First name'),
    '#default_value' => ''
  );
  $form['last_name'] = array(
    '#type' => 'textfield',
    '#title' => t('Last name'),
    '#default_value' => ''
  );
  $form['content'] = array(
    '#type' => 'textarea',
    '#title' => t('Content'),
    '#default_value' => ''
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Save')
  );

  return $form;
}