<?php

function cv_maker_init() {
  drupal_add_css(drupal_get_path('module', 'cv_maker') . '/cv_maker.css');
}

function cv_maker_perm() {
  return array('access test content');
}

function cv_maker_menu() {
  $items = array();

  $items['home'] = array(
    'title' => 'Homepage',
    'description' => 'Home page',
    'page callback' => 'get_homepage',
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM
  );
  $items['new-cv'] = array(
    'title' => 'New CV',
    'description' => 'Form for creating new CV',
    'page callback' => 'get_new_cv_form',
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM
  );

  return $items;
}

function get_homepage() {
  $cv_list = views_embed_view('cvs', 'block_1');
  $link = l('Add', 'http://cv-maker.lo/new-cv');
  return theme('cv_list_homepage', $cv_list, $link);
}

function cv_maker_theme() {
  return array(
    'views_view_fields__cvs__block_1' => array(
      'arguments' => array('view' => NULL, 'options' => NULL, 'row' => NULL, 'field_alias' => NULL),
      'original hook' => 'views_view_fields',
      'template' => 'views-view-fields--cvs--block-1',
      'preprocess functions' => array('template_preprocess_views_view_fields', 'cv_maker_preprocess_views_view_fields')
    ),
    'cv_list_homepage' => array(
      'template' => 'cv-list-homepage',
      'arguments' => array('cv_list' => 'List of CVs is empty', 'link' => NULL)
    )
  );
}

function get_new_cv_form() {
  return drupal_get_form('new_cv_form');
}

function new_cv_form($form_state) {
  $form = array();
  $form['credentials'] = array(
    '#type' => 'fieldset',
    '#title' => t('Credentials'),
    '#collapsible' => FALSE,
    '#collapsed' => FALSE,
  );
  $form['credentials']['first_name'] = array(
    '#type' => 'textfield',
    '#title' => t('First name'),
    '#default_value' => ''
  );
  $form['credentials']['last_name'] = array(
    '#type' => 'textfield',
    '#title' => t('Last name'),
    '#default_value' => ''
  );
  $form['content'] = array(
    '#type' => 'textarea',
    '#title' => t('Content'),
    '#default_value' => ''
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Save')
  );

  return $form;
}

function new_cv_form_submit($form, $form_state) {
  $node = new stdClass();

  $node->title = 'cv_'
    .strtolower($form_state['values']['first_name'])
    .'_'
    .strtolower($form_state['values']['last_name']);
  $node->field_first_name[0]['value'] = $form_state['values']['first_name'];
  $node->field_last_name[0]['value'] = $form_state['values']['last_name'];
  $node->field_content[0]['value'] = $form_state['values']['content'];
  $node->type = 'cv';
  $node->created = time();
  $node->changed = $node->created;
  $node->status = 1;          // Published?
  $node->promote = 0;       // Display on front page?
  $node->sticky = 0;          // Display top of page?
  $node->format = 1;         // Filtered HTML?
  $node->uid = 1;             //  Content owner uid (author)?
  $node->language = 'en';

  node_save($node);
}