<?php

function cv_maker_perm() {
  return array('access test content');
}

function cv_maker_menu() {
  $items = array();

  $items['home'] = array(
    'title' => 'Homepage',
    'description' => 'Home page',
    'page callback' => 'get_homepage',
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM
  );
  $items['new-cv'] = array(
    'title' => 'New CV',
    'description' => 'Form for creating new CV',
    'page callback' => 'get_new_cv_form',
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM
  );

  return $items;
}

function get_homepage() {
  return 'Hello!';
}

function get_new_cv_form() {
  return drupal_get_form('new_cv_form');
}

function new_cv_form($form_state) {
  $form = array();
  $form['credentials'] = array(
    '#type' => 'fieldset',
    '#title' => t('Credentials'),
    '#collapsible' => FALSE,
    '#collapsed' => FALSE,
  );
  $form['credentials']['first_name'] = array(
    '#type' => 'textfield',
    '#title' => t('First name'),
    '#default_value' => ''
  );
  $form['credentials']['last_name'] = array(
    '#type' => 'textfield',
    '#title' => t('Last name'),
    '#default_value' => ''
  );
  $form['content'] = array(
    '#type' => 'textarea',
    '#title' => t('Content'),
    '#default_value' => ''
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Save')
  );

  return $form;
}
